.\" Copyright (c) 2011-2014 Yubico AB
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions are
.\" met:
.\"
.\"     * Redistributions of source code must retain the above copyright
.\"       notice, this list of conditions and the following disclaimer.
.\"
.\"     * Redistributions in binary form must reproduce the above
.\"       copyright notice, this list of conditions and the following
.\"       disclaimer in the documentation and/or other materials provided
.\"       with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
.\" "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
.\" LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
.\" A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
.\" OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
.\" SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
.\" LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
.\" DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
.\" THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
.\" OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.\" The following commands are required for all man pages.
.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..
.if \n[.g] .mso www.tmac
.TH ykchalresp "1" "Febuary 2011" "yubikey-personalization"
.SH NAME
ykchalresp - Perform challenge-response operation with YubiKey
.SH SYNOPSIS
.B ykchalresp
[\fI-1\fR | \fI-2\fR] [\fI-H\fR] [\fI-Y\fR] [\fI-N\fR] [\fI-x\fR] [\fI-v\fR] [\fI-6\fR] [\fI-8\fR] [\fI-t\fR] [\fI-V\fR] [\fI-h\fR]
.SH DESCRIPTION
.PP
Send a challenge to a YubiKey, and read the response.  The YubiKey can be configured
with two different C/R modes -- the standard one is a 160 bits HMAC-SHA1, and the other
is a YubiKey OTP mimicing mode, meaning two subsequent calls with the same challenge
will result in different responses.
.SH OPTIONS
.TP
\fB\-1\fR
send the challenge to slot 1.  This is the default.
.TP
\fB\-2\fR
send the challenge to slot 2.
.TP
\fB\-H\fR
send a 64 byte HMAC challenge.  This is the default.
.TP
\fB\-Y\fR
send a 6 byte Yubico OTP challenge.
.TP
\fB\-N\fR
non-blocking mode -- abort if the YubiKey is configured to require a key press before
sending the response.
.TP
\fB\-x\fR
challenge is hex encoded.
.TP
\fB\-v\fR
enable verbose mode.
.TP
\fB\-6\fR
output the response in OATH format, 6 digits.
.TP
\fB\-8\fR
output the response in OATH format, 8 digits.
.TP
\fB\-t\fR
use current time as challenge instead of reading challenge from command line (as in default TOTP mode, seconds since 1970-01-01 00:00:00 / 30 encoded as an 8 byte challenge).
.TP
\fB\-V\fR
print tool version and exit.

.SH EXAMPLE
The YubiKey challenge-response operation can be demonstrated using the
\fBNIST PUB 198 A.2\fR test vector.
.P
First, program a YubiKey with the test vector :
.HP
.nf
$ \fBykpersonalize \-2 \-ochal\-resp \-ochal\-hmac \-ohmac\-lt64 \-a 303132333435363738393a3b3c3d3e3f40414243\fR
 ...
Commit? (y/n) [n]: y
$
.fi
.HP
Now, send the NIST test challenge to the YubiKey and verify the result matches the
expected :
.HP
.nf
$ \fBykchalresp \-2 'Sample #2'\fR
0922d3405faa3d194f82a45830737d5cc6c75d24
$
.fi

.SH BUGS
Report ykchalresp bugs in
.URL "https://github.com/Yubico/yubikey-personalization/issues" "the issue tracker"
.SH "SEE ALSO"
The
.URL "https://developers.yubico.com/yubikey-personalization/" "ykpersonalize home page"
.PP
YubiKeys can be obtained from
.URL "http://www.yubico.com/" "Yubico" "."
