.\" Copyright (c) 2011-2014 Yubico AB
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions are
.\" met:
.\"
.\"     * Redistributions of source code must retain the above copyright
.\"       notice, this list of conditions and the following disclaimer.
.\"
.\"     * Redistributions in binary form must reproduce the above
.\"       copyright notice, this list of conditions and the following
.\"       disclaimer in the documentation and/or other materials provided
.\"       with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
.\" "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
.\" LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
.\" A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
.\" OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
.\" SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
.\" LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
.\" DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
.\" THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
.\" OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.\" The following commands are required for all man pages.
.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..
.if \n[.g] .mso www.tmac
.TH ykinfo "1" "October 2012" "yubikey-personalization"
.SH NAME
ykinfo - Get basic information from a YubiKey
.SH SYNOPSIS
.B ykinfo
[\fI-s\fR] [\fI-m\fR] [\fI-H\fR] [\fI-v\fR] [\fI-t\fR] [\fI-p\fR] [\fI-1\fR] [\fI-2\fR] [\fI-q\fR] [\fI-V\fR] [\fI-h\fR]
.SH DESCRIPTION
.PP
Get basic information from a YubiKey. Can get serial number, version
and current touch level. Can get all parameters at once or one at a
time.  If \fB\-q\fR is given only the relevant string from the YubiKey
is written to screen.
.SH OPTIONS
.TP
\fB\-s\fR
get the serial number and output it.
.TP
\fB\-m\fR
get the serial number and output it as modhex.
.TP
\fB\-H\fR
get the serial number and output it as hex.
.TP
\fB\-v\fR
get the version and output it.
.TP
\fB\-t\fR
get the touch level and output it.
.TP
\fB\-p\fR
get the programming sequence and output it.
.TP
\fB\-1\fR
get the status of slot 1, 1 for programmed and 0 for empty.
.TP
\fB\-2\fR
get the status of slot 2, 1 for programmed and 0 for empty.
.TP
\fB\-a\fR
get all the information above.
.TP
\fB\-c\fR
get YubiKey capability information.
\fB\-q\fR
modifier, only show the relevant data from the YubiKey, no extra information.
.TP
\fB\-V\fR
print tool version and exit

.SH EXAMPLE
Output of all information from a YubiKey

.nf
$ \fBykinfo \-s \-m \-H \-v \-t \-p\fR
serial: 1077254
serial_hex: 107006
serial_modhex: bcicch
version: 2.2.3
touch_level: 1793
programming_sequence: 1
$
.fi

.SH BUGS
Report ykinfo bugs in
.URL "https://github.com/Yubico/yubikey-personalization/issues" "the issue tracker"
.SH "SEE ALSO"
The
.URL "https://developers.yubico.com/yubikey-personalization/" "ykpersonalize home page"
.PP
YubiKeys can be obtained from
.URL "http://www.yubico.com/" "Yubico" "."
